[package]
name = "todos"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.22.0"
egui = "0.22"
egui_extras = { version = "0.22", features = ["image"] }
image = { version = "0.24", features = ["jpeg", "png"] }
